name: "spike-land-mcp: Build & Test"

on:
  push:
    branches: [main]
    paths:
      - "packages/spike-land-mcp/**"
  pull_request:
    paths:
      - "packages/spike-land-mcp/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: packages/spike-land-mcp
        run: npm install

      - name: Typecheck
        working-directory: packages/spike-land-mcp
        run: npm run typecheck

      - name: Test
        working-directory: packages/spike-land-mcp
        run: npm test
